[package]
name = "cdm-json-validator"
version = "0.1.1"
edition = "2024"
license = "MPL-2.0"

[dependencies]
serde_json = "1.0"
cdm-plugin-interface = { path = "../cdm-plugin-interface" }
cdm-utils = { path = "../cdm-utils" }

[dev-dependencies]
cdm = { path = "../cdm" }
