[package]
name = "cdm-json-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
cdm-plugin-interface = { path = "../cdm-plugin-interface" }
cdm-utils = { path = "../cdm-utils" }

[dev-dependencies]
cdm = { path = "../cdm" }
